# Generated by Django 5.0 on 2023-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_remove_chatmessage_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
