# Generated by Django 5.0 on 2023-12-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatroom_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='room_name',
        ),
    ]
