# Generated by Django 5.0 on 2023-12-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_room_chatmessage_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room_name',
            new_name='room',
        ),
    ]
