# Generated by Django 5.0 on 2023-12-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_room_name_chatmessage_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
